### ISSUE TITLE
Possible to create a blog like Scripting.com

### ISSUE THREAD

**Issue by postmarkme** [scripting/Scripting-News#107]
[Here](https://github.com/scripting/Scripting-News/tree/master/blog) Dave says he uses littleoutliner to write his blog. "To publish changes to the outline, on the blog," he explains, "I click an icon. This sends an HTTP call to the server saying "update the site." It has been told where the OPML file is, and has all the prefs set in a local config file. It then generates a folder of JSON and HTML files representing the days, items and pages of the site. From this data, the renderer can generate the home page, the story pages, and the monthy and daily archive pages.

OK, sounds great. How do I set this up? Has Dave explained how? Is the code he uses available? 

(What icon does he click on? How does the server get set up? What else other than littleoutliner is being used here?)

Sorry, I am a kind of newb.

**Comment by scripting** [comment]
Technically you could do it, but it's not something I've documented or am supporting.
