### ISSUE TITLE
Raw JSON appearing in Scripting News pages

### ISSUE THREAD

**Issue by tedchoward** [scripting/Scripting-News#11]
When I scroll to the bottom of the page, and then try to keep scrolling, I see a screen full of escaped JSON.

![screen shot 2017-06-15 at 9 20 17 am](https://user-images.githubusercontent.com/470549/27185743-e10f82ec-51ab-11e7-8581-85fa5870f85b.png)

**Comment by scripting** [comment]
The usual drill applies -- what browser, machine, etc.

I'm not seeing it in Chrome on my Mac.

**Comment by tedchoward** [comment]
Safari Technology Preview on MacOS "Sierra" (I also saw this behavior in Chrome)

This is the url http://scripting.com/2017/06/15.html

It's not happening now.

**Comment by scripting** [comment]
I hate it when problems are not reproducible.

I'll keep an eye out for it.

And in general flaws in my site are not easter eggs. ;-)

**Comment by scripting** [comment]
I just got it here. 
![image](https://user-images.githubusercontent.com/1686843/27254629-0730c422-535a-11e7-896d-bece5792ac87.png)

**Comment by scripting** [comment]
And fixed.

http://scripting.com/2017/06/17.html#a120659

Dave
