### ISSUE TITLE
Firefox: "sign on" error

### ISSUE THREAD

**Issue by stijnsanders** [scripting/Scripting-News#114]
A click in the 'sign on' link top left gives this in the console:

    ReferenceError: toggleConnect is not defined

and nothing happens.

    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by stijnsanders** [comment]
Error occors in daytemplate.js line 486, in function chatToggleConnect

**Comment by scripting** [comment]
Thanks for the report. I think I have fixed the problem. Be sure to hard-reload the scripting.com home page, and try again and let me know if it works.

**Comment by stijnsanders** [comment]
Yup, that did it! thanks 1e6
