### ISSUE TITLE
A browser JavaScript challenge

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#116]
Here's a <a href="http://scripting.com/playingcards/">demo app</a>. 

Use the up and down arrow keys to move from card to card. When you get to the bottom of the screen the cursor moves to objects that are not visible. I want to scroll the window vertically to make the cursor object fully visible. 

If you look at <a href="http://scripting.com/playingcards/code.js">the code</a>, the goal is to fill in the body of the _scrollToMakeVisible_ routine.

**Comment by ouchiko** [comment]
```function scrollToMakeVisible (idObjToMakeVisible) {
var el = document.getElementById(idObjToMakeVisible);
var t = el.offsetTop;
var h = el.offsetHeight;
    var j = parseInt(window.scrollY) + parseInt(window.innerHeight);
    if (t<window.scrollY) {
        window.scrollTo(0,(window.scrollY-h));
    } else if ((t+h)>=j) {
        window.scrollTo(0,(window.scrollY+h));
    }
}```

**Comment by ouchiko** [comment]
```
function scrollToMakeVisible (idObjToMakeVisible) {
var el = document.getElementById(idObjToMakeVisible);
var t = el.offsetTop;
var h = el.offsetHeight;
    var j = parseInt(window.scrollY) + parseInt(window.innerHeight);
    if (t<window.scrollY) {
        window.scrollTo(0,(window.scrollY-h));
    } else if ((t+h)>=j) {
        window.scrollTo(0,(window.scrollY+h));
    }
}
```

**Comment by scripting** [comment]
@ouchiko -- thanks for the solution. I've added it to the app.

**Comment by scripting** [comment]
Except it doesn't work as you hit the uparrow to move the cursor off the top of the screen. It only partially scrolls to make the item visible, and after a few scrolls it isn't making the item visible at all. I reopened the thread.

**Comment by jmgs** [comment]
I build on what @ouchiko wrote with two more refined solutions that don't show the drifting: the second is generic, the first looks better but only works if all elements have the same height.

```
///////////////////////////////////////////////////////////////////
// This solution relies on all cards having the same height
// and the gap between cards being the same. It is more satisfying
// because cards don't "jump" when the screen scrolls.
///////////////////////////////////////////////////////////////////

idOfFirstCard = "img0";
idOfSecondCard = "img1";

function scrollToMakeVisible (idObjToMakeVisible) { 
	var card = document.getElementById(idObjToMakeVisible);
	var cardTop = card.offsetTop;
	var cardHeight = card.offsetHeight;
	var cardGap = getCardGap();
	var windowTop = window.scrollY;
	var windowHeight = window.innerHeight;	

	if (cardTop < windowTop - cardGap) {
		window.scrollTo(0, cardTop);
	} else if (cardTop < windowTop) {
		window.scrollTo(0, windowTop - cardGap);
	}
	
	if (cardTop + cardHeight > windowTop + windowHeight + cardGap) {
		window.scrollTo(0, cardTop + cardHeight - windowHeight);
	} else if (cardTop + cardHeight > windowTop + windowHeight) {
		window.scrollTo(0, windowTop + cardGap);
	}
}
	
function getCardGap() {
  var y0 = document.getElementById(idOfFirstCard);
  var y1 = document.getElementById(idOfSecondCard);
  return y1.offsetTop - y0.offsetTop;
}


///////////////////////////////////////////////////////////
// This solution works even if cards have different height
///////////////////////////////////////////////////////////

function scrollToMakeVisible (idObjToMakeVisible) { 
	var element = document.getElementById(idObjToMakeVisible);
	var elementTop = element.offsetTop;
	var elementHeight = element.offsetHeight;
	var windowTop = window.scrollY;
	var windowHeight = window.innerHeight;	

	if (elementTop < windowTop) {
		window.scrollTo(0, elementTop);
	}
	
	if (elementTop + elementHeight > windowTop + windowHeight) {
		window.scrollTo(0, elementTop + elementHeight - windowHeight);
	}
}
```

**Comment by ouchiko** [comment]
True, the height of the `<img>` tag is used and doesnt account for the margin which ends up being a floating point height value.  Slightly refined with the actual height point adjusted.  You could use the `element.parentNode` for height but I was looking for a more generic routine.

```
function scrollToMakeVisible (idObjToMakeVisible) {
	var el = document.getElementById(idObjToMakeVisible);
	var t = el.offsetTop;
	var h = 137.4; //el.offsetHeight;
    var j = parseInt(window.scrollY) + parseInt(window.innerHeight);
    if (t<window.scrollY) {
        window.scrollTo(0,(window.scrollY-h));
    } else if ((t+h)>=j) {
        window.scrollTo(0,(window.scrollY+h));
    }
}
```

**Comment by tommy-carlier** [comment]
DOM-elements have a method scrollIntoView that does this for you:

    function scrollToMakeVisible(idObjToMakeVisible) {
      var el = document.getElementById(idObjToMakeVisible);
      el.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }

See documentation at https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by scripting** [comment]
@tommy-carlier -- that worked and it makes total sense that the browser, in 2019, would have this feature built-in. No need for every app to do it for itself. Thanks.

**Comment by scripting** [comment]
I also added the ability to click on a card to move the cursor to it. It was driving me nuts that it didn't work. Now the case is closed. This will be part of a new app I'm working on. Thanks to @ouchiko, @jmgs and @tommy-carlier for the generous help! :-)
