### ISSUE TITLE
RSS-in-JSON: enclosure.length as string or number?

### ISSUE THREAD

**Issue by brentsimmons** [scripting/Scripting-News#12]
In the README it’s a string — but that seems like it might be a typo, since a number would be expected there.

Checked the schema: it says enclosure.length is an integer. (If I read it right, that is. I’m not practiced at reading JSON schema.)

**Comment by scripting** [comment]
I've asked a couple of wise people for their opinions, but in the meantime I thought I'd ask my blogging software, and it says the spec is wrong as currently written. ;-)

http://scripting.com/rss.json

Here's the item that contains the test podcast. 

```
{
   "link": "http://scripting.com/2017/06/26.html#a010633",
   "description": "From time to time I have to do a podcast to test things out. This is one of those times. Let's see what happens. ",
   "pubDate": "Mon, 26 Jun 2017 17:29:33 GMT",
   "guid": "http://scripting.com/2017/06/26.html#a010633",
   "enclosure": {
      "url": "http://scripting.com/2017/06/26/yetAnotherTestPodcast.m4a",
      "type": "audio/mpeg",
      "length": 277413
       }
   }
```
As you can see, it thinks that length is a number not a string. 

Dave

**Comment by danmactough** [comment]
@scripting 😄 This is the same comment I emailed to you a few weeks ago. I think that's when you updated your feed (or maybe the actual feed always did that, but I guess the readme still ). @brentsimmons I think we're all in agreement that `enclosure.length` is an integer.

Dave, I made a PR to update the readme #13

**Comment by scripting** [comment]
Dan, thanks for checking in. I made the change.

https://github.com/scripting/Scripting-News/commit/2347bb8751d94dc76d25074997db4fde682585f9#diff-d8d0ec34e3943d3fdcd53a3e40217023

Dave
