### ISSUE TITLE
Header frame overlays text on printed page

### ISSUE THREAD

**Issue by WmHBlair** [scripting/Scripting-News#121]
When printing a web page at scripting.com, such as [http://scripting.com/2017/03/08/theWorldIsSocialistPartIi.html](url),
text from the "header" frame overlays the printed output of the page itself, sometimes causing the printed text to be unreadable.
![1 - web page](https://user-images.githubusercontent.com/34389465/62329373-544fbe00-b47b-11e9-9da6-3d7929221184.jpg)
![2 - Printed page 1](https://user-images.githubusercontent.com/34389465/62329377-587bdb80-b47b-11e9-805c-c0249b724239.jpg)
![3 - printed page 2](https://user-images.githubusercontent.com/34389465/62329382-5ade3580-b47b-11e9-8ef0-c3064d68578c.jpg)

**Comment by scripting** [comment]
Thanks for the report.

But --

1. That template and CMS was retired a long time ago. 

2. Those pages are archives and will never be rebuilt.

2. Back when it was the current CMS, printing was never a priority.
