### ISSUE TITLE
Help test the new email subscribe/unsubscribe

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#129]
I'm ready for a test of the new email subscription code.

First, this test will not affect whether or not you're subscribed. It is just a test.

1. Go to <a href="http://scripting.com/email/testing/">this page</a>, enter your email address, click the button.

2. Check your email. If you have a confirming email, click the link. 

3. If this worked, unsubscribe using a link of this form:

http://scripting.com/email/testing/?unsub=true&email=you@somewhere.org 

where you replace the email address with your own. This is the email address that will be in the Unsubscribe link at the bottom of each email.

Let us know if it worked, though I will be able to see if it has from the server. If there are problems, please say what happened, as specifically as you can. Thank you.

**Comment by fspin** [comment]
Just subscribed. But the first link I received expired. I didn't know this will happen... Maybe you want to add that in the email you send the people subscribing.

I wonder what is the reason to make the link expired? I will understand the link expired if the link was clicked.

**Comment by scripting** [comment]
I'm going to increase the expiration to 1/2 hour from 5 minutes.

I want to expire it because I don't want it taking up memory on the server if someone did it by accident.
