### ISSUE TITLE
In Node, piping a post results in garbage added

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#130]
I have a server running in Node that responds to HTTP POSTs. 

It's being invoked through [PagePark](http://pagepark.io/) using its ability to delegate requests. Here's the [actual code](https://github.com/scripting/pagePark/blob/master/pagepark.js#L539) that does the delegation.

The message is transmitted to the proper server, it handles it properly, responds as it's supposed to, and PagePark transmits the response, with one problem. _It adds extra characters before and after the response._ 

[Here's a gist](https://gist.github.com/scripting/f33b859bad09f8f087b339b2357b0070) containing the actual response. 

The characters added at the beginning of the response: 1f7

And at the end: 0

I have to admit I don't understand what the piping is doing, and I haven't found a way to debug this. So I'm looking for either possible answers, or possible ways to debug.

**Comment by PeterJudge-PSC** [comment]
It's http chunking. Note the transfer-encoding header and lack of content-length. It's in the rfc https://tools.ietf.org/html/rfc7230#section-4.1

**Comment by scripting** [comment]
@PeterJudge-PSC -- thank you. That was exactly right.

I added a Content-Length header to the response from the server, and now it all works well.

Interesting to note -- It's an XML-RPC handler, and the [XML-RPC spec](http://xmlrpc.scripting.com/spec.html) clearly says the response must include a content-length header. Also it was a bug in my implementation of the client side that it didn't understand chunks. And my discomfort with pipes led me to believe the problem was probably there. It wasn't. ;-)

![image](https://user-images.githubusercontent.com/1686843/64130249-19e58380-cd8f-11e9-8a61-5e375e28e39a.png)
