### ISSUE TITLE
Pagination missing / Load-more doesn't work?

### ISSUE THREAD

**Issue by jtomaszewski** [scripting/Scripting-News#133]
Hey Dave! I like your blog. I had just read it all over until I reached the end of the page ;) ... which surprisingly resulted to be Sep 20, 2019 :( After that once I scroll down, I don't see anything more than just the footer in which you describe the nightly email newsletter.

![image](https://user-images.githubusercontent.com/1862580/66778693-be99cb80-eecc-11e9-9423-cec0a47ec6f9.png)

Is this desired? Is there a way to reach the older articles on your blog?

**Comment by scripting** [comment]
We have never had that feature, honestly I had never thought of doing it, so thanks for the suggestion.

I've used a lot of different content management systems over the years, so I don't think it's likely to ever happen. But it might be possible to go back to May of 2017, when the current system was built.

In the meantime, every month has its own archive page. For example, this is the archive page for September of 2018.

http://scripting.com/2018/09/

In general going back over the years, most months have archive pages, some are in this form.

http://scripting.com/2012/07.html

Generally for most months its one or the other. 

Hope this helps.
