### ISSUE TITLE
New feature: "infinite" scrolling on home page

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#136]
There's now a More button at the bottom of the Scripting News [home page](http://scripting.com), if you click the button, you'll get another page from the Scripting News archive, going back as far as May 2017, when the current CMS came online.

You can also vertically scroll past the end and it'll do it without you having to click the button. It's a little tricky because there's so much text at the bottom.

**Comment by leiferksn** [comment]
Looks like More button is not loading previous content with Firefox 72.0.2 (64-Bit) on Windows. Probably because of the host, the request is sent to? 
![screen](https://user-images.githubusercontent.com/4026636/73285768-d173aa00-41f6-11ea-82ea-73b22d4ce3be.png)

**Comment by scripting** [comment]
do you see any errors in the javascript console?

not sure what you mean by the host. what's wrong with the host?

**Comment by leiferksn** [comment]
hi,

by host I mean not a valid URL (no slashes), but I see what you mean :) - the domain name contains 'http'. it's totally valid. didn't thought about it that way. still, I don't get a respons to the 'More' request. 

httpproxy.scripting.com/httpReadUrl?url=http%3A%2F%2Frockaway.scripting.com%3A1400%2Fday%3Fblog%3Ddave%26day%3DTue%2C%2031%20Dec%202019%2022%3A37%3A15%20GMT&type=text%2Fplain

as for the javascript errors - don't see any. just some warnings.

**Comment by scripting** [comment]
That gave me the clue I needed, and I fixed the problem. 

Thanks for the report and for persisting. ;-)
