### ISSUE TITLE
Main tabs are not unique URLs

### ISSUE THREAD

**Issue by spilth** [scripting/Scripting-News#139]
When I visit http://scripting.com/ I expect to end up on the Blog tab of the site but it always puts me on the last tab I was on. It also means I can't use keyboard navigation or the browser's Back buttons to get to the page I was previously on. This feels contrary to how browsers and web sites should work.

**Comment by scripting** [comment]
Thanks for the feedback. The title of your comment is confusing. Each tab
does have a unique url.

http://scripting.com/?tab=blog

That said, there's no way you could know that unless you read the blog on
the day the feature was introduced.

I'll think about whether or not to forget which tab you were at last.
Probably not that useful a feature now that we've cut down the number of
tabs so much.

It also remembers how the About outline was expanded. How do you feel about
that?

**Comment by spilth** [comment]
Sorry for the confusing title. To be clearer, when I click the navigation tabs at the top of the page (Blogs, Links, About), I expect the URL in the browser's address bar to change, as well as end up in my browser's history. This allows me to use my browser's Back button to get to the previous page.

I suspect the Navigation functionality is related to other issue I opened up about it: https://github.com/scripting/Scripting-News/issues/123

For a little more insight, frequently I Command-Tab to my browser, press Command-T to open up a new tab, start typing `scripting.com` and press Return to go to the site. I'm off the mouse and just want to use the keyboard to navigate both the tabs, links and browser history. I realize I may be in the minority in browsing this way but also feel like it's standard usability for a web site, IMHO. 🤷‍♂ 

I don't frequently use the About page, so I don't have strong opinions about it remembering what is expanded or not.

**Comment by sillygwailo** [comment]
The way to do this is to use HTML5's History API, i.e. whenever someone clicks on a tab, update the URL as well. It keeps the back and front buttons working while on the site. Some links:

* https://stackoverflow.com/questions/6118693/how-can-i-change-the-page-url-without-refreshing-the-page
* https://medium.com/young-coder/a-simple-introduction-to-the-history-api-in-javascript-85b879d3d87e

**Comment by spilth** [comment]
Woo! Thanks!

**Comment by scripting** [comment]
It was a good feature request and over time I came to agree with you. When I finally got around to doing it, it was a relatively easy fix. So thank you, and let me know if you have any more. ;-)

PS: Wash your hands!
