### ISSUE TITLE
Markdown for an HTTP request

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#140]
I am writing docs that includes an HTTP request example. 

The docs are written in Markdown. 

I'm trying to figure out how to format it so that it looks roughly like this:

http://scripting.com/code/xmlrpc/requestexample.html

Any help much appreciated.

**Comment by kantel** [comment]
It depenced on the dialect of Markdown you are using. Most Markdown dialects supports blocks of code either in three backticks <code>```</code> or in tildes `~~~`. So if You write this

~~~
```xml
POST /RPC2 HTTP/1.0
	User-Agent: Frontier/5.1.2 (WinNT)
	Host: betty.userland.com
	Content-Type: text/xml
	Content-length: 181
	
	<?xml version="1.0"?>
	<methodCall>
		<methodName>examples.getStateName</methodName>
		<params>
			<param>
				<value><i4>41</i4></value>
				</param>
			</params>
		</methodCall>
```
~~~

You should get this: 

```xml
POST /RPC2 HTTP/1.0
	User-Agent: Frontier/5.1.2 (WinNT)
	Host: betty.userland.com
	Content-Type: text/xml
	Content-length: 181
	
	<?xml version="1.0"?>
	<methodCall>
		<methodName>examples.getStateName</methodName>
		<params>
			<param>
				<value><i4>41</i4></value>
				</param>
			</params>
		</methodCall>
```

**Comment by scripting** [comment]
Jorg, thanks for the help -- this is for GitHub.

What can we do about the indent under the POST? 

It doesn't belong there.

**Comment by kantel** [comment]
It was an error of mine, I just didn't ident the POST. Now it should be fixed.

**Comment by scripting** [comment]
It is fixed. I did it in a GIST too. 

https://gist.github.com/scripting/c4ee12eeacfff323bba67fc4fe662d73

**Comment by kantel** [comment]
👍

**Comment by scripting** [comment]
Here's what I'm working on. 

https://github.com/scripting/xml-rpc/blob/master/spec.md

Dave

**Comment by tedritzer** [comment]
Hi Dave
I used RadioUserland and loved it, FYI I have posted an article on an open source IOT standard article that may be of interest re XML:
https://medium.com/sensorup-blog/more-developer-friendly-and-agile-geospatial-standards-exciting-developments-from-the-113th-ogc-9315da9e85dd?

Ted Ritzer
