### ISSUE TITLE
Text file icon in latest font-awesome?

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#147]
Is there an icon like this: 

![image](https://user-images.githubusercontent.com/1686843/73276502-c8fb7f00-41b6-11ea-8638-ec9950c425dd.png) 

in the current version of Font-Awesome? I'd like to upgrade to the latest, but without this or something very close to it, I can't.

**Comment by sgjudd** [comment]
How about https://fontawesome.com/icons/file-alt?style=regular

**Comment by scripting** [comment]
@sgjudd -- thanks that looks perfect. 

Now I feel like I've been down this road before. 

I'm going to try, this time, to straighten out all my Font Awesome stuff. I wish they wouldn't move stuff around, it breaks apps. ;-)

**Comment by clartaq** [comment]
Have you considered using something like [fontello](http://fontello.com) to create a custom font with the only the icons you need? That way you could grab the icons you want, create the font, and serve it without having to load FA or worry about them moving glyphs around.

I've used this a couple of times (including the exact same icon you were looking for) and it saves a lot of headaches.

**Comment by scripting** [comment]
Thanks for the suggestion and the help. I had a similar idea. I'm going to
develop a simple layer on top of Font Awesome to isolate my use of it, and
make it easy to update next time they change things.

I have a lot of other plates in the air and that's as much as I can
contemplate right now.
