### ISSUE TITLE
NPM is behaving weirdly?

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#165]
0. I have a fair amount of experience writing and submitting modules to NPM. 

1. This new module, davezip, isn't working.

2. I require it in the usual way, do an npm install, and run the app, and get an error. 

`Error: Cannot find module 'davezip'`

3. I verify that the folder is in node_modules, and it contains the correct files.

4. I also note that a few of the files have the mod date Oct 26, 1985 at 4:15 AM. See screen shot at end of this list. 

5. Here's a minimal program that displays the problem. It's just one line. 

`const myzip = require ("davezip");`

6. Not sure what else I can try. Any help much appreciated. 

![image](https://user-images.githubusercontent.com/1686843/79132986-4a57bc00-7d79-11ea-9f62-1353378b2af2.png)

**Comment by papascott** [comment]
Just created a test project and I did not get the error

1. mkdir daveziptest ; cd daveziptest
1. npm -y init
1. npm install davezip
1. create file index.js
```
const myzip = require("davezip");
console.log(myzip);
```
1. node index.js 
`{ createArchive: [Function] }`

ls -l node_modules/davezip
```
-rw-r--r--  1 shanson  staff  1032 Oct 26  1985 davezip.js
-rw-r--r--  1 shanson  staff  1239 Apr 13 17:34 package.json
-rw-r--r--  1 shanson  staff    87 Oct 26  1985 readme.md
-rw-r--r--  1 shanson  staff   575 Oct 26  1985 readme.opml
```

**Comment by scripting** [comment]
I found the problem -- I left out the "main" section of the package.json file.

Not the first time I;'ve made that mistake. 

@papascott -- I think you must've tried it after I fixed it. Sorry for the wild goose chase! :-)
