### ISSUE TITLE
Hello World for WordPress

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#179]
I want to write a very simple Node.js client for the current version of WordPress. It needs to, using the current REST API:

1. Create a new WordPress post.

2. Update an existing post. 

```
const wordpress = require ("wordpress");

const myBlog = wordpress.getBlog (<authentication>);

var thePost = myBlog.postMessage ("Hello world", "This is a hello world post.");

thePost.update ("Hello World!", "This is the updated text for the Hello World post.");
```

That's the basic idea.

Has anyone written such a hello world app?

What's the best package to use?

How do I get the authentication information for a specific blog on wordpress.com? I want to know what to put in the docs for my users. And of course I have to use it to test it myself.

Thanks in advance. ;-)

PS: This is the kind of stuff we used to do with the [MetaWeblog API](http://1998.xmlrpc.com/metaWeblogApi.html).

**Comment by iolaire** [comment]
It seems obvious but have you seen this package? https://github.com/scottgonzalez/node-wordpress 

All the WordPress automation these days is via   https://codex.wordpress.org/XML-RPC_WordPress_API

I used it a good bit in the mid 2000's via Ruby but not recently.

**Comment by scripting** [comment]
@iolaire, I did see it, but it hasn't been updated to use the new API. It uses the XML-RPC API. I already have code for that. But it's not current.

**Comment by iolaire** [comment]
Interesting I didn't know about the move to the Rest API.

**Comment by trconsulting** [comment]
This looks like it would do the job, and is from Automattic. 

http://wpcomjs.com/

There is source for editIng a post on the Github repository.

https://github.com/Automattic/wp-calypso/tree/master/packages/wpcom.js

**Comment by scripting** [comment]
The first example doesn't post or update. It reads the content of a site, useful -- but it isn't what I need to do.

The second link is to the API toolkit, which I'm sure contains the answer, somewhere, in some fashion. I wanted a Hello World example. Is it possible that people no longer know what that means??

https://en.wikipedia.org/wiki/%22Hello,_World!%22_program

I can't believe a hugely popular product like WordPress that has a new API doesn't have the equivalent of a Hello World example that creates and updates a post. It has to be there somewhere.

**Comment by TimothyBJacobs** [comment]
Hello @scripting,

You'll probably want the `node-wpapi` package: https://github.com/WP-API/node-wpapi. The client supports basic auth, but that isn't built in to WordPress yet and requires an [external plugin](https://github.com/wp-api/Basic-Auth). A more robust [authentication solution](https://github.com/WP-API/authentication/projects/2) is in-progress for WordPress Core.

That is all for WordPress Core, the open source solution. You mentioned WordPress.com in your post as well. WordPress.com has its own [API](https://developer.wordpress.com/docs/api/). It also supports the WordPress Core REST API at a URL of `https://public-api.wordpress.com/wp/v2/sites/{site_id}/`. So you could create a post at `https://public-api.wordpress.com/wp/v2/sites/{site_id}/posts`. If you are connecting to a WordPress.com site, I believe you can use WordPress.com's OAuth2 implementation, but I haven't tried this myself. https://developer.wordpress.com/2016/11/11/wordpress-rest-api-on-wordpress-com/

The Core REST API is documented here: https://developer.wordpress.org/rest-api/

**Comment by pwiner** [comment]
I did this by writing directly to the Wordpress MySQL database. I can give you the code. It’s a short command line script. You have to supply the MySQL credentials and the ID of the post. These are command line parameters to the script.

**Comment by scripting** [comment]
@pwiner -- thanks for the offer, but that wouldn't work in this situation. I need to go through the API. This is for a product, Radio3. It used to be able to cross-post to WordPress, but they changed the API. I need the equivalent code but for the new API. My users don't typically have access to the machine running WP, or the database credentials.

**Comment by scripting** [comment]
@TimothyBJacobs -- I'm beginning to get the idea that this isn't workable. Shame, because the original API could do this. You could hook up an external authoring tool to WordPress. I was hoping to find a path in. I'm going to leave this here, hoping that at some point someone will produce a simple Hello World app that does what I want.

**Comment by JimGoodman** [comment]
There is a WP-CLI that I use to update my sites, etc. and I know it has some post/page manipulation available to it... it might get you down the road a bit further, maybe?

**Comment by scripting** [comment]
Bing. This time I got something to work, using the first suggestion above from @iolaire. Back in a bit with the code that resulted in a hello world post actually making it to a wordpress site. :smile:

**Comment by scripting** [comment]
Here's the Hello World app.

https://github.com/scripting/wordpressHelloWorld/blob/main/wordpresshelloworld.js

Glad to get this mofo done. Now we can use it in various apps. ;-)
