### ISSUE TITLE
Longevity of Existence?

### ISSUE THREAD

**Issue by userLevel** [scripting/Scripting-News#202]
Have you ever considered the notion of providing the user's of littleoutiner with some degree of comfort that it's not just gong to disappear tomorrow, as so very many of your whims, which people use and then lose their information (e.g., Fargo)? I can't bring myself to use littleoutiner even though it very much is what I want because I have no confidence I'll be able to log on tomorrow. Plus not knowing where/how the data is stored and the sign-in via twitter is extremely irritating—at least use something like Google's sign in, something that non–idiots use (maybe not all twitter users are idiots, but the percentage is extremely high). Maybe consider following in the footsteps of 37 Signals/Basecamp:

https://basecamp.com/about/policies/until-the-end-of-the-internet

**Comment by scripting** [comment]
Thanks for the concern. There's a command in the Tools menu to download all your outlines.

Here's a screen shot. 
![image](https://user-images.githubusercontent.com/1686843/110029470-80d85580-7d02-11eb-9fda-ab9faa31ce27.png)

Fargo never stored copies of your files, they were in Dropbox, if you recall. When Fargo shut down, your files were still there, in a standard file format.
