### ISSUE TITLE
Setting up PagePark on node.js using Digital Ocean

### ISSUE THREAD

**Issue by brandon-toner** [scripting/Scripting-News#217]
Background/Context: https://github.com/scripting/Scripting-News/issues/210#

After failing to get PagePark running on the Glitch server, I'm now trying to get it running on Digital Ocean. I'm using this as an opportunity to learn some command line, and continue learning about the fundamentals of how the web works — ultimately with the goal of setting up a running web server. 

Documenting progress and questions below.

**Comment by brandon-toner** [comment]
Steps completed so far: 

1. Setup droplet
2. Created and used SSH key
3. Accessed the server via my Mac command line
4. Installed node.js
5. Installed npm

References:
- [Installing node.js on Ubuntu](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04)
- [Generating an SSH key](https://www.youtube.com/watch?v=ncua01HTxis)

**Comment by brandon-toner** [comment]
So now the next step I need to figure out is how to install PagePark onto this server. 

Observations: 
- It seems that all of the setup on Digital Ocean is via the command line. Whereas Glitch features a GUI to support installation.

Questions:  (more rhetorical than anything at this point, just thinking out loud here to organize my thoughts)
1. On pagepark.io, the steps seem to outline the process for deploying the PagePark server on a local machine. How does the process differ for deploying in the Digital Ocean Ubuntu environment?
2. Is there a guide published anywhere for installing PagePark in this sort of environment?

References:
- http://pagepark.io/

**Comment by brandon-toner** [comment]
Of course, trying to proceed to `npm install` without having the PagePark file package on the server returns an error.

So, how do I download the [PagePark file package](https://github.com/scripting/pagepark/archive/master.zip) to the server so that it can be opened, facilitating the install of the PagePark server?

**Comment by brandon-toner** [comment]
> "So, how do I download the PagePark file package to the server so that it can be opened, facilitating the install of the PagePark server?"

I think this is the wrong question. As commented in #210, I think I need to figure out how to ["point Digital Ocean at the repo for PagePark"](https://github.com/scripting/Scripting-News/issues/210#issuecomment-864607567).

**Comment by scripting** [comment]
Good morning Brandon. Glad to see you're back at it. Eventually you will get there. I'll put a pointer to this on scripting.com so hopefully others will come to help.

First, you need to be sure a git client is installed on your server. 

`sudo apt-get install git`

If that doesn't work, here's the [Digital Ocean doc](https://www.digitalocean.com/community/tutorials/how-to-install-git-on-ubuntu-20-04) on installing git. 

Then cd to the directory you want to install PagePark in and enter this command:

`git clone https://github.com/scripting/pagePark.git`

If that goes well, next thing to do is to

`npm install`

Then edit your config.json file, as needed, I use the nano editor:

`nano config.json`

And then...

`node pagepark.js`

One thing to consider is, if you use Dropbox on your desktop computer, to install it on the server, then copying things to the server is just a matter of downloading stuff on your desktop and copying it into the server's folder.

**Comment by brandon-toner** [comment]
> First, you need to be sure a git client is installed on your server.
Done.

> Then cd to the directory you want to install PagePark in and enter this command:
Done. (~/pagePark)

> npm install
Done.

> Then edit your config.json file, as needed, I use the nano editor:
No edits made yet.

> node pagepark.js
Server is running.

**Comment by brandon-toner** [comment]
In following the instructions in the README.md file:

> 4. Create a sub-folder of the domains folder called localhost.

Done.

> 5. Using a text editor add a file to the localhost folder called index.md. Put whatever you like in the file. Save it.

I'm stuck here. Not sure how to create and add the file to the localhost directory.

> if you use Dropbox on your desktop computer, to install it on the server, then copying things to the server is just a matter of downloading stuff on your desktop and copying it into the server's folder.

I use Google Drive, I suspect that is able to be used as well. This is likely my answer for getting files onto the server.

**Comment by brandon-toner** [comment]
> I use Google Drive, I suspect that is able to be used as well.

Dropbox seemed more straightforward. So I've installed **Dropbox** and have it connected to my account.

**Comment by scripting** [comment]
As far as I know there is no Ubuntu client for Google Drive. That's what you'll have to find.

Next, you're following the instructions for getting PP running on your desktop system. That won't work on the server. 

localhost is a special name. You should look it up on the web. I'm sure you'll find plenty of explanations. ;-)

Anyway, I'm rushing out the door, so don't have the time to write a tutorial here, but maybe someone else can help.

The goal is to figure out what the name of your computer is. Same thing as before. You have to map one of your domains to this machine. Then instead of "localhost" put the name of the domain. To edit text, use nano, as I described in the earlier message. I'm sure they have a tutorial on nano on Google.

**Comment by brandon-toner** [comment]
Ok I've successfully setup Dropbox, and copied an "index.md" file into ~/pagePark/domains/brandontoner.ca

I think now I need to make sure the DNS settings are correct such that brandontoner.ca is pointing to the server.

**Comment by brandon-toner** [comment]
As for the DNS settings:

- On Digital Ocean's Control Panel I have an A Record (hostname: domain; Value: directs to droplet IP).
- On Namecheap (domain registrar) I have: custom DNS setup as per Digital Oceans docs.

References:
- [Digital Ocean: A Records](https://docs.digitalocean.com/products/networking/dns/how-to/manage-records/)
- [Digital Ocean: Namecheap](https://www.digitalocean.com/community/tutorials/how-to-point-to-digitalocean-nameservers-from-common-domain-registrars)

![image](https://user-images.githubusercontent.com/67168828/125467519-2788911b-6d5e-4168-b23a-af19fc153293.png)
![image](https://user-images.githubusercontent.com/67168828/125467556-7853ed94-2e77-40b7-8497-11d0931558d2.png)

**Comment by scripting** [comment]
Don't forget this --

https://github.com/scripting/pagePark#mapping-port-80-to-1339

**Comment by brandon-toner** [comment]
Woah progress!! 

I think I'm connected to the server correctly now. My file didn't render, but I did get the PagePark error message for file not found.

> https://github.com/scripting/pagePark#mapping-port-80-to-1339

Did this, then tried = failed.
Then I changed to the pagepark directory, ran `node pagepark.js` to start the server, in case it wasn't activated. = This screen.

![image](https://user-images.githubusercontent.com/67168828/125530021-1ae50c91-8b23-41e9-96f6-ed60da0d553d.png)

**Comment by brandon-toner** [comment]
Re: "File not found".

The index.md file is located in the brandontoner.ca domain folder... not sure why it wouldn't render.

Unless something needs to be adjusted in the config.json?

![image](https://user-images.githubusercontent.com/67168828/125530641-74c59215-446c-481e-8efc-059c223656b1.png)

**Comment by brandon-toner** [comment]
> I think I'm connected to the server correctly now.

Confirmed. I'm seeing traffic from my local network when I call the page!
![CleanShot 2021-07-13 at 19 01 00@2x](https://user-images.githubusercontent.com/67168828/125531061-eebb2282-c5c6-413f-b18e-3dc027ae76a3.png)

**Comment by scripting** [comment]
I just went to http://brandontoner.ca/ and saw "hello world" -- so i guess you got all the glitches ironed out. ;-)

**Comment by brandon-toner** [comment]
Woohoo! That's good news.

So now I suppose I could try to setup those mirrors to get the live publishing from Little Outliner 2.

What are the steps for getting that configured?

**Comment by brandon-toner** [comment]
> What are the steps for getting that configured?

Figured it out! Modelled after your pagepark.glitch.me project you shared in #210.

Now I just need to re-write the content and mirrors so they display as intended. But the nuts and bolts are in place.

**Next goal: Setup a blogging template similar to scripting.com**

**Comment by scripting** [comment]
Keep on truckin! ;-)

I'm so swamped, I wish I could help. 

I wish some others would come play with you.

**Comment by scripting** [comment]
I just checked how pagepark.glitch.me works, and it's good -- it uses the "mirrors" feature, the one I fixed so it would work for what you're doing. I'm glad that that helped. Here's a screen shot of what's in the config.json file of that domain on Glitch.

![image](https://user-images.githubusercontent.com/1686843/125645754-00f9e550-10a2-48e7-9d08-de8e7625920e.png)

**Comment by brandon-toner** [comment]
Success.

I wrote a simple index.html, added the mirrors and the links work on testing! 

![image](https://user-images.githubusercontent.com/67168828/125652608-5c386ea1-42d4-4ea1-bf02-372426745f79.png)

**Comment by mistersugar** [comment]
@brandon-toner Well done and kudos to you!

What are you mirroring for the blog.opml page? Is it a public link to a LittleOutliner outline?

**Comment by brandon-toner** [comment]
Ok I'm returning back to this after a while — and feeling a little rusty on how to operate PagePark. 

Goal: I have a domain name for our pharmacy business and I'd like to upload some basic pages to display on that url. 

After some mucking around today, I figured out how to log into my Digital Ocean Droplet via Terminal on my MacOS.
- `ssh root@{IP address of the droplet}` (I already had the SSH key setup.

Next, re-figure out how to point my domains to PagePark.

Going to explore the directory now to see what jogs my memory.

**Comment by brandon-toner** [comment]
The domain I'm trying to activate is www.medicineshoppesydney.ca.
- It seems I've already connected it to PagePark (it's listed under domains, and displays placeholder content)

<img width="444" alt="image" src="https://user-images.githubusercontent.com/67168828/188931555-51479a04-2446-414e-bb8f-80b853cdbede.png">
<img width="840" alt="image" src="https://user-images.githubusercontent.com/67168828/188931641-4f5a1955-0a03-4870-a878-0e99d7e4f14d.png">

Next question: How did I get that index.md page loaded?
- My guess is Dropbox. (It's connected and referenced in these threads as a way to upload content)

Next question: How do I use Dropbox on Terminal? 
....

**Comment by brandon-toner** [comment]
I really wish I could see a full history of the commands run on this server. A little trip back through that log would be HELPFUL right now.

**Comment by brandon-toner** [comment]
Ok, I can see the contents of the index.md file reflect the content displaying live when calling the URL. 

<img width="569" alt="image" src="https://user-images.githubusercontent.com/67168828/188935572-63a1b5ba-67b9-4665-9682-370e0bca8bfc.png">

So that's promising. I'm re-learning how to navigate the server using command line. That's good.

**Comment by scripting** [comment]
Brandon, you're misusing this  resource. It's a place to report issues with this specific product, PagePark.

**Comment by brandon-toner** [comment]
Ok, noted.
