### ISSUE TITLE
Safari 9.1.3 can't see the links page or the hamburger list/menu

### ISSUE THREAD

**Issue by michaelshopsin** [scripting/Scripting-News#22]
In Safari 9.1.3 on MacOS X 10.11.6 the hamburger icon on the top left side of the Scripting.com website is supposed to reveal a menu/list of links. The list of links does not open when you
click on the hamburger icon in Safari 9.1.3 but does work in Firefox 55.0. Even if I use the direct url http://scripting.com/links.html the links page does not load.

![scriptingnewsbadlinks](https://user-images.githubusercontent.com/4006638/29275938-e147d422-80da-11e7-9419-75fcab6ed973.PNG)

**Comment by scripting** [comment]
Michael thanks for the report.

I tried it in my desktop Safari, v10.1 and it worked.

Also the Links page is different from what's revealed under the hamburger icon. It's the linkblog page. Maybe the names are confusing. I rush by these questions when I'm building the software. ;-)

![image](https://user-images.githubusercontent.com/1686843/29276048-4d6c8fbc-80db-11e7-9eda-a6c2a807057a.png)
