### ISSUE TITLE
Untangling the opml.org mess

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#221]
Re this blog post. 

http://scripting.com/2021/08/16/131002.html?title=undoingTheOpmlorgRedirectMess

Comments go here...

**Comment by scripting** [comment]
The problem is nowhere near as bad as I thought it would be. 

I did a poll.

https://twitter.com/davewiner/status/1427273264485781511

No one is getting the cached redirect but me.

**Comment by scripting** [comment]
My browser, Chrome/Mac, is  redirecting to http://dev.opml.org. 

Because...

1. http://opml.org used to be an S3 bucket.

2. It was redirected to http://dev.opml.org, using the S3 web server.

**Comment by papascott** [comment]
If you don't want Chrome to delete your entire cache, I think you can trick Dev Tools into clearing just the redirect...

- Press SHIFT+CTRL+I to open the Google Chrome Developer Tools panel.
- Go to the Network tab and select the "Disable cache" checkbox to enable that feature.
- Type the URL you want to clear from the browser cache in the address bar and press Enter.
- Click and hold the reload button until a modal window pops up, the select the "Empty Cache and Hard Reload" hidden option.
-  As soon as the page has been fully reloaded, you can unselect the "Disable cache" checkbox and disable that feature.

via https://www.ryadel.com/en/clear-google-chrome-redirect-cache-for-single-url-page-howto/

**Comment by scripting** [comment]
@papascott --exactly right. i got the same advice on twitter, it worked. ;-)

amazing how jumbled my mind gets, i always do that when i'm working on browser-based apps to load new code, but didn't think to apply it here. oy. 

onward!
