### ISSUE TITLE
Features Request: single click, import/export markdown, 

### ISSUE THREAD

**Issue by auwsom** [scripting/Scripting-News#225]
Any chance to have a single click to toggle expand/collapse as the blog carrots do?

Or import/export from/to markdown? Copy and paste of '2 space indented' outline for importing does work. And so does pasting rendered outline (from basic GitHub Page) with indents in '4 spaces' form (bullets are not copied). However the standard asterisk or dash marked nested indents would paste those characters. Exporting would be great 

Btw, `Ctrl+?` doesnt work in my stock Firefox browser on Ubuntu. Shift+Ctrl+

Nevermind, the page keeps freezing up.. making it unusable. I'll try to track down what's causing that, but I already tried changing my network with same result. Assuming its a read/write bottleneck from twitter, or a client side slowdown, but this machine has plenty of unused resources.

Yep, seems to freeze while saving. 
Switching to Workflowy(only 250 bullets per month free) or dynalist.io or Vimflowy or HackFlowy

**Comment by scripting** [comment]
@auwsom -- thanks for the suggestions. i don't know what's causing the freezes, lots of people are using Drummer, haven't had one report of that before this. It's possible you have a plugin of some kind in your browser that's interfering. Good luck. ;-)

**Comment by auwsom** [comment]
Thanks Dave. I'll check out Drummer. Dynalist seems to be working pretty well for me.

**Comment by scripting** [comment]
I am interested in import of markdown files. Could you provide some examples of files you think we should be able to handle.

**Comment by auwsom** [comment]
Thanks Dave. The main idea is using most simplest form of formatting for info organizing. To me that is a tree structure, or nested lists. (Tags are helpful for interconnections like neurons) And I really like folding/collapsing for readability.

Markdown can carry this kind of organization with Header level, but better with lists, which can be nested like an outline. (https://en.wikipedia.org/wiki/Markdown) There's numbered and bulleted lists. The latter is either * or -, or even tabs or spaces. I think 2 spaces is the simplest, see below. 

So then keeping that essential organization is important to me. Mainly for export, so my info isnt trapped. And then importing for interoperability. I tested Little Outliner and it does take this format, and copied rendered bulleted info (mentioned above). I couldnt export except into opml. Which I did. I like your work a lot. Found it lots of years ago. Dynalist seems to have a Backup download that has both opml and a tab/space outlined opml.txt file. 

Just following the KISS method so I can use the info in the most situations or environments from bash/vim to online editing and sharing.

```
one
  two 
    three
  four
```

**Comment by auwsom** [comment]
https://rwx.gg/lang/md/basic/ 
https://www.twitch.tv/rwxrob
good stuff :+1:

**Comment by scripting** [comment]
I know markdown, I need actual example files that you’ve tried to import that didn’t work properly.

**Comment by auwsom** [comment]
That was an example above, the ' one two three four' part. I meant it does import when I said "it does take this format" and in the first message, simply by pasting it in. It doesn't export and it didn't look like I could copy it out because of the inability to select multiple lines by dragging mouse (maybe on the published page, but it was freezing up).

**Comment by auwsom** [comment]
I wanted to share this with you in case you thought it interesting to have interoperability with JSON. The headings are keys for that sections text. And markdown outlines are put into nested lists:
https://github.com/njvack/markdown-to-json
