### ISSUE TITLE
Formats matter more than software

### ISSUE THREAD

**Issue by docum3nt** [scripting/Scripting-News#257]
"Too often people try to design a format first, and then make software that conforms to the format. "

This is actually the correct way to do it. The industry is littered with the corpses of software where the designer jumped the gun and failed to do a proper analysis of the requirements of the user and their data.

For a given application, I don't want 1,000 different data formats but only one piece of software.
For a given application, I only want one data format, and a wide choice of software to handle it. 
If that data format later turns out to be good for lots of other applications, so much the better.

**Comment by scripting** [comment]
Post this on your site and send me a link.
