### ISSUE TITLE
Scripting News home page broken, AWS 503 (Slow Down) error

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#27]
This is what the home page [looks like](http:///scripting.com/images/2017/09/14/scriptingHomeScreen.png) right now. 

In the console I see there's an error 503 (slow down) on reading the CSS file. 

http://fargo.io/code/shared/oldschool/daytemplate.css

From what I can see it's an infrequent error. Going to see what more I can learn.

**Comment by scripting** [comment]
The problem went away on its own.

**Comment by johnspurlock** [comment]
There was an s3 outage in us-east-1 for about an hour earlier today: https://status.aws.amazon.com/
