### ISSUE TITLE
Problems with Electric Pork feed upload

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#3]
Some people report problems with their feed. 

It's observable on the server, very few user feeds are showing up.

If you know how the console works in JavaScript, you can help me figure out what's going wrong. 

1. Create a test post. Publish it. 
2. Look in the console. If it worked, you'll see something like this. If it didn't work, you should see an error message. Please post a screen shot here, so I can see. 

![image](https://cloud.githubusercontent.com/assets/1686843/23834037/d56f735a-0725-11e7-9ce0-cdf8e252a98f.png)

**Comment by papascott** [comment]
I got a 500 error, here's the screenshot 
![screenshot_336](https://cloud.githubusercontent.com/assets/8681117/23843829/af84ab44-07be-11e7-9a70-c740f3051a71.png)

**Comment by scripting** [comment]
Thanks Scott. That's useful info. It looks like all the credentials are being transmitted and since the tweets went out, it's clear that Twitter liked them. Unfortunately I'm not getting any info about what went wrong on the server. I have a theory I'm going to test. Will report back.

**Comment by scripting** [comment]
I found the problem and just have to implement the fix. 

The problem: The Electric Pork app shares a nodeStorage server with the web app. But this can't work because EP doesn't have a whitelist and the web app does. 

The people who were whitelisted for the web app are getting their RSS feeds written and people who aren't whitelisted aren't. Sometimes it just takes patience to cut through the fog. ;-)

**Comment by scripting** [comment]
Okay the server has been updated, and this problem should now be fixed. Please try again, and let me know if it does. Thanks! :-)

**Comment by papascott** [comment]
Yes, it works! http://pork.io/users/papascottpork/rss.xml :-)

**Comment by scripting** [comment]
Awesome. Thanks so much Scott, you are the #1 tester. ;-)

BTW, if you log off and log back on that will make the tokens you posted here earlier obsolete.

**Comment by papascott** [comment]
Happy to be able to help. :-)
