### ISSUE TITLE
280 characters for radio3.io?

### ISSUE THREAD

**Issue by papascott** [scripting/Scripting-News#41]
Will radio3.io be getting 280 characters? 😄

**Comment by scripting** [comment]
It works now. You should always test these things before reporting them. And if it doesn't work, provide steps to reproduce.

**Comment by papascott** [comment]
Sorry, the counter shows 140 so I assumed it hadn't been implemented...
![screenshot_499](https://user-images.githubusercontent.com/8681117/32622335-d361939c-c582-11e7-8ab9-85be161c546e.png)

**Comment by scripting** [comment]
I understand. 

However, nothing has been implemented, it "just works." 

And I kind of like leaving the counter as-is at least for a while. I've been discussing this on Twitter, that it's not such a bad idea for it to turn red when you cross 140 chars and go negative. Anyway, I'm thinking about it so this thread is good to leave here.

**Comment by scripting** [comment]
I went ahead and changed the constant from 140 to 280. So now it behaves exactly as before, and only goes red when it hits 280. Thanks for the report. ;-)
