### ISSUE TITLE
How should I add shows to BingeWorthy?

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#46]
Now that [BingeWorthy](http://bingeworthy.io/) is released, I'm thinking about next steps. 

Here's the number one topic of interest and feature request --

> There are lots of programs that aren't on BingeWorthy. I'm thinking of ways to open it up to new programs, preferably ways that don't require too much editorial involvement on my part. Do you have any ideas or suggestions? 

You can use this thread to nominate programs if you want. And if you agree with a suggestion, give it a thumbs up.

**Comment by scripting** [comment]
I just added [Godless](http://bingeworthy.io/?id=00353), the new Netflix show, to BingeWorthy. Once it gets 5 ratings it will be eligable for the hotlist. A highly-rated Netflix program is pretty much an automatic add.

**Comment by ttepasse** [comment]
If I were you and would be sufficiently motivated: I'd allow users to add shows they want to vote on.

Of course freeform entry is a recipe for small disasters, different shows that are named the same, typos, etc. Better would be a search out of which users can pick the show. That would need a database of existing shows. There is one, [TheTVDB](https://en.wikipedia.org/wiki/TheTVDB). A hypothetical search-and-add feature for BingeWorthy could use TheTVDB's JSON Api as a backend service. Another TV-related web service that I use – [watched.li](https://watched.li/user/index) – does the same.

(At the moment of this writing TheTVDB seems to be down which is of course not a great advertisement. But in the past it was pretty solid and more importantly mostly complete.)

**Comment by robin-scott** [comment]
In terms of "uniqueness" what about hooking into IMDB or similar? I used their API many moons ago for movies site; they have most TV shows on there.

**Comment by scripting** [comment]
Every program has an ID in the world of BingeWorthy.

Here's the current list -- 

http://db.bingeworthy.org:1401/getprograms

Dave

**Comment by robin-scott** [comment]
@scripting cool - was referring more to the issue of user submissions mentioned by @ttepasse (i.e. they will typo things!) so if there were (say) an IMDB lookup to ensure correct program title added, that works. Or just moderation.

**Comment by scripting** [comment]
I read your comment and understood it @robin-scott -- my comment was not a response to yours. 

Just adding data to the thread.

**Comment by frankleahy3** [comment]
Page where anyone can make a suggestion, and link it to IMDB.

If IMDB has a search API, this linking could happen automatically because you would let users search for shows on Bingeworthy.  That way too they can't add shows that don't exist.

Once a show is added to the suggestion page, at least 5 different people have to "thumbs up" the suggestion before it's added to the master list.

**Comment by charlie-payne** [comment]
I would handle it similarly to Frank. Let users create a requested show list on their own account and when X users have requested the same show, add it automatically.

TVmaze has a REST API with a show lookup call that returns JSON. This could be used to avoid the problem of the same show being given multiple names in requests.

https://www.tvmaze.com/api#show-lookup

**Comment by nitinthewiz** [comment]
Dave, if all it takes to add a program is to add its name, then a suggestion box on the site would work just fine, specially if you can automate the process of pulling in those suggestions and importing valid ones to your db.

If it takes a little more than that, then why not have the data as a JSON in its own github repo, and people can send you pull requests to add new programs? That's how most services crowdsource data.

There could be two ways to do this - 
1. The person just forks your repo, sends a pull request with the names they want to add.
2. The person forks your repo, which includes a json file and a rudimentary script. They add the names, run the script, which pings some API to verify the name is correct, then appends the data it found to the json file. Then they send you a pull request.

**Comment by scripting** [comment]
You all realize what you're proposing is basically another BingeWorthy for
recommending programs to add to BingeWorthy?

It's like the movie inception. ;-)

Dave

**Comment by scripting** [comment]
I appreciate all the comments, I'm going to close the thread though -- I think this is something that has to involve people who would not be able, or willing to put the effort into learning how to be part of an open source community and a source control system.
