### ISSUE TITLE
Paragraph anchors on titled items on their own pages point back to the daily archive page

### ISSUE THREAD

**Issue by sardisson** [scripting/Scripting-News#56]
Now that titled items also have their own pages, would it make sense on those pages to have the paragraph anchors set up for and reference that page, rather than pointing back to the daily archive page?

E.g., if I want to link to the last paragraph of "About patriarchy and gender", which now additionally lives in a self-contained form on http://scripting.com/2017/12/28/153110.html, I can only do so via http://scripting.com/2017/12/28.html#a153320, which bumps me back off of the "About patriarchy and gender" post page and on to the December 28th archive page.  This seems sub-optimal when you're already on a small, focused page.

**Comment by sardisson** [comment]
Actually, at the moment it looks like anchors are broken entirely, as the anchor names are currently full URLs rather than just the anchor fragment, e.g.
<a name="http://scripting.com/2017/12/28.html#a153320"></a>
instead of 
<a name="a153320"></a>
so that you don't get jumped the the appropriate paragraph anywhere (on month/day/item pages) due to the broken anchor names.

Maybe the behavior I don't like in the initial comment is a consequence of the anchors being broken entirely.

**Comment by scripting** [comment]
Thanks for the report. You are correct the permalinks for subitems of titled items are crazy. 

I fixed the problem, as [reported here](http://scripting.com/2017/12/30/152920.html). 

Let me know if you agree the problem is fixed, and thanks again! :-)

**Comment by sardisson** [comment]
The issue I first saw (first comment) seems corrected, but it seems like the anchor names are still broken (second comment), because I still don't get jumped directly to the correct paragraph.  

I checked the source again, and anchor names still appear to be full URLs rather than just the "aNNNNN" bit they were before the titled-items-getting-their-own-page-changes, and nothing I've tried jumps to paragraphs.  (By comparison, pre-December month/day pages all still have their paragraphs' anchor names in the "aNNNNN" format and following one of those links jumps me exactly to the paragraph, e.g. both http://scripting.com/2017/11/30.html#a205509 or http://scripting.com/2017/11/#a205509 )

**Comment by scripting** [comment]
Sorry about that -- I didn't get that there were two problems. I think I've fixed the <a name> issue. 

An example -- 

http://scripting.com/2017/12/29/160005.html#a160116

Dave

**Comment by sardisson** [comment]
Yep, looks good now, thanks.  Sorry I wasn't clear enough about that second problem initially.

**Comment by scripting** [comment]
I really appreciate the report, and the way you did it. I want to rely on the management functions of GitHub, for the blog.
