### ISSUE TITLE
Problem with Axios RSS feed(s)

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#61]
[Observed](https://twitter.com/cbasturea/status/955283668091789312) over the weekend, the &lt;link> elements in main Axios RSS feed (possibly others) points to /feeds/. This is not correct for a couple of reasons:

1. It's not a fully qualified URL.

2. It if were interpreted as a relative URL it points to _feeds_ not an article. 

Here's a screen shot of the current contents of the feed.

![image](https://user-images.githubusercontent.com/1686843/35227334-d7dca4f8-ff5b-11e7-9ee9-f883fcccdbdf.png)

**Comment by ctbarna** [comment]
Hey Dave, Constantin reached out and let us know about the issue. It should be resolved now. Can you let me know if you're still having issues?

**Comment by scripting** [comment]
Chris, thanks for checking in. 

Yes, it's working now. I checked a link posted about an hour ago and it took me to the [correct story](https://www.axios.com/rupert-murdoch-goes-after-google-facebook-abb910fa-313d-4694-a140-95f1a1ade01c.html). 

I love Axios. Keep up the good work! ;-)

**Comment by jpstephens83** [comment]
What is the RSS Address for Axios?  My feed broke in reeder app for the mac and I can't find a way to re-add it?

**Comment by scripting** [comment]
Here's the feed.

http://www.axios.com/feeds/feed.rss

Dave

**Comment by jesserifkin** [comment]
I literally created a GitHub account today just so I could ask this question. Is there an RSS feed _just_ for the Mike Allen newsletter Axios AM? Using the general RSS feed which works, I've tried every variation I could find by insert **mike-allen** or **axios-am** into the URL, but nothing seems to work. Can anybody please help me here? I use RSS feeds almost exclusively for my news, and I've been looking for an RSS feed of that morning newsletter for more than a year since it first launched.

**Comment by ScootRay** [comment]
Jesser, if there’s no such feed you may want to check out Feedbin which supports sending email newsletters to you via RSS.

**Comment by jesserifkin** [comment]
Thanks for the tip, but Feedbin appears to be $5 per month with a 14-day free trial. I use NetVibes which is 100% free, all the time. Alas, there doesn't seem to be a email-newsletter-to-RSS-feed feature on NetVibes, as far as I can tell.

If anybody reading this thread, even months in the future, knows of a good way to get Axios AM or any other newsletter into a free generally-usable RSS feed, I'm sure I'm not the only one who would appreciate it!

**Comment by alecpage** [comment]
I'm going to try https://www.kill-the-newsletter.com/ - looks promising at first glance.
