### ISSUE TITLE
How to create a simple MySQL report?

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#63]
I'm using MySQL. I have a little experience with MySQL, it's the database I use in BingeWorthy. 

I have a project similar to BingeWorthy, involving different data and I want to do a little more with it. I've encountered a conceptual hurdle and am hoping someone here can help. 

There are three tables, _orders, products_ and _customers_. In this example we are only interested in orders and products. We want to know which are the most popular products and rank them from most popular to least popular. The resulting report should show the product name and the number of orders. 

Products and customers both have id's, and they are different. The product whose ID is 12 is not the same as customer 12 (obviously). 

A row in _orders_ has two fields: customer ID and product ID. It may have other fields, but they're not important for this example.  

A row in _products_ has two fields: product ID and product name (a string). And of course other fields, like how much is in inventory, and who we use as a vendor, etc, but they are not important for this example.  

The goal is to produce a report with two columns, the name of the product and the number of times orders for the product.  

```+--------------------------------------------------------+-----------+
| product                  | count     |
+--------------------------------------------------------+-----------+
| Flat screen TV           |         9 |
| iPhone X                 |         8 |
| Blackberry yogurt        |         7 |
| Tesla car                |         6 |
| Movie ticket             |         6 |
```

That's the problem. It must be such a common thing for SQL databases. Combining information from two tables to produce a report.

**Comment by bennywij** [comment]
Do a “join” between orders and product. Something like... (without knowing more about the tables... for example I’m not sure if you need the distinct, does a product appear more than once in a given order? If so you probably want the distinct count)

SELECT p.product_name
   , count(DISTINCT o.id) as count_unique_orders
FROM orders o
  JOIN products p
    ON o.product_id = p.product_id
ORDER BY count(DISTINCT O.id) DESC

**Comment by elroyjetson** [comment]
I put in all my table assumptions and some dummy data, but you can create the report using GROUP BY.  I bolded the query that is the actual answer.

**select products.product_name, COUNT(*) as count FROM products, orders WHERE orders.product_id = products.product_id GROUP BY orders.product_id;**


Output:

+-------------------+-------+
| product_name        | count   |
+-------------------+-------+
| Flat screen TV        |     3      |
| iPhone X                 |     3      |
| Blackberry yogurt  |     3      |
| Tesla car                 |     1      |
| Movie ticket           |     1      |
+-------------------+-------+

Assumptions on database definition:

CREATE TABLE IF NOT EXISTS products (
  product_id INT(11) NOT NULL AUTO_INCREMENT,
  product_name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (product_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
  order_id INT(11) NOT NULL AUTO_INCREMENT,
  customer_id INT(11) NOT NULL,
  product_id INT(11) NOT NULL,
  PRIMARY KEY (order_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS customers (
  customer_id INT(11) NOT NULL AUTO_INCREMENT,
  customer_name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (customer_id)
) ENGINE=InnoDB;

INSERT INTO `products` (`product_name`) VALUES 
("Flat screen TV"), 
("iPhone X"),     
("Blackberry yogurt"),
("Tesla car"),  
("Movie ticket"); 

INSERT INTO `customers` (`customer_name`) VALUES 
("George Jetson"), 
("Jane Jetson"),     
("Elroy Jetson"),
("Astro Jetson");

INSERT INTO `orders` (`customer_id`, `product_id`) VALUES 
(1,1), 
(1,2),     
(1,3),
(1,4),
(2,1), 
(2,2),     
(2,3),
(2,5),
(3,1), 
(3,2),     
(3,3);

**Comment by scripting** [comment]
You guys got it!

Thanks @bennywij and @elroyjetson!!!

It's working here now and I can move on.

You guys are the best. ;-)

**Comment by bennywij** [comment]
Yay! Embarrassingly for me of course I forgot the “group by” clause which should go before the “order by” but Elroy’s query got it right.

**Comment by fwmiller** [comment]
I like Benny's query a little better.  Its sorting uses order by rather than group by.  Group by will  potentially collapse the values one column (in Eloy's case on orders.product_id.  There's a possibility, (depending on the redundancy in your data, that some rows might be lost.  But this is quite subtle and may not occur.

**Comment by scripting** [comment]
I'm going to release the source for this app shortly, it would be great to have you review the actual implementation. Watch the [blog](http://scripting.com/) for a pointer. ;-)
