### ISSUE TITLE
Windows AMI with GUI pre-installed

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#7]
I'm trying to find a Windows AMI on Amazon that boots up into the desktop. I don't want to have to install a GUI.

https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=public-images;ownerAlias=amazon;platform=windows;sort=name

Used to be they all booted into the GUI. 

It's been a while since I've provisioned a Windows server.

Any help much appreciated.

**Comment by jalefkowit** [comment]
Search the AMI list for "Desktop Experience" and you should get back a bunch of AMIs (including official ones from Amazon) for Windows Server with the GUI included. It looks like the most recent one with the English-language version of Windows is AMI ID ami-f1b5cfe7.

**Comment by TomLoyal** [comment]
Dave,
You want the Microsoft Windows Server 2016 Base - ami-f1b5cfe7. That one includes the desktop experience. When I clicked launch instance from the EC2 Dashboard it was the fifth one on the list. See below:  https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard: 

Oops, I see jalefkowit  beat me to it.  Good luck!

**Comment by scripting** [comment]
Jason, Tom -- it worked. I have a Windows 10 desktop running. It's a very foreign beast. Last Windows I used was XP.

First thing I did was install Chrome. That worked fine.

Next Dropbox. It installed and it's downloading all the files, which is not what I want it to do

I am looking for the Dropbox app so I can fiddle around with selective sync, but I can't for the life of me find the Dropbox app. 

I clicked on everything named Dropbox in the Start menu but they all just open the Dropbox folder. I want the app so I can configure it. 

Any help appreciated..

**Comment by jalefkowit** [comment]
Windows 10 supports type-to-search in the Start menu, so open it up and just start typing "Dropbox" and it should bring you back a list of everything named Dropbox on the system, including the shortcut to the app (assuming one exists).

Note: all my (limited) Win10 experience has been with the workstation flavor, not Server, so it's possible there's Server-specific wrinkles here. But AFAIK the Start menu is the Start menu in both.

**Comment by jalefkowit** [comment]
It may also be worth noting that there appear to be two distinct versions of Dropbox available for Windows 10: "Dropbox desktop client," which is what you get if you download the installer from dropbox.com, and "Dropbox for Windows 10," which is what you get if you [install Dropbox from the Windows App Store.](https://www.microsoft.com/en-us/store/p/dropbox/9wzdncrfj0pk?rtc=1) I'm not sure if there are any actual differences between the two, but if you're using one and it behaves unexpectedly, it might be worth trying the other instead.

**Comment by TomLoyal** [comment]
On getting around in windows 10... Right clicking the "start" button will bring up a menu with common system apps like control panel, and the command prompt. Not easily discoverable but quite useful once you know its there.

Ps. I'm running River5 as a service under Windows. Works great and my wife likes her river of sci-fi blogs. Thanks for your work!

**Comment by scripting** [comment]
Thanks for all the help!

I'll try to answer the questions you all ask and let you know how I decided to go.

1. I tried the type-to-search capability. It was so slow as to be unusable and it didn't even find the Dropbox folder containing the files, certainly not the Dropbox app that would allow me to selectively unsync all of the folders (huge) it was trying to sync which is probably why search was so slow. I bet the disk was filling up. AMIs typically have very small virtual hard disks.

2. I need to run a "legacy" app that I haven't yet ported to Node, so how Node works on Windows is not important. If I were using Node I'd just have it run on one of my Linux installations. 

3. I have the app running on an XP instance, from back in the EC2 for Poets days. Amazed that it still works. I got the app running so quickly I had time to think about running it on a modern version of Windows. I guess that was a mistake. They changed the UI so much as to make it unrecognizable. So it isnt really an option for me now. Linux feels more friendly. That's saying something!

4. I will keep the app running on XP for now, and will convert it when I have the time to Node. I killed the instance running Windows 10. So that's the end of this little saga.

5. Again thanks for the help! You guys are the best. I'm going to use GitHub more now that I have the new blog format and no easy place to put a Disqus thread.

**Comment by owenmorris** [comment]
For what it's worth, if you do ever go back to Server 2016, the Dropbox program runs in the system tray.  You can get to it by clicking on the upward pointing chevron on the right hand side of the task bar (near the clock).  Right click on the icon and it'll open the status window.

<img width="313" alt="screen shot 2017-06-02 at 18 32 37" src="https://cloud.githubusercontent.com/assets/352802/26737474/2b884622-47c2-11e7-9b77-c53117b48d18.png">

**Comment by scripting** [comment]
Owen -- haha -- I should have guessed that, but I was so discombobulated. If it had presented more or less like Windows I probably would have thought of that. ;-)

**Comment by owenmorris** [comment]
For what it's worth, when I set up this machine (which was in Azure, but the steps should be the same for AWS), I:

1. Clicked on Local Server in Server Manager.  Clicked 'Internet Explorer Protected Mode' and turned it off.  Minimised Server Manager.
2. Opened up Internet Explorer and went to Dropbox.  Downloaded the app and ran the install.
3. Selected it from the task bar as per the screenshot above.

That's pretty much all you should need to do.  After that I normally install my common software using [chocolatey](https://chocolatey.org/install).
