### ISSUE TITLE
Getting iconv into my feed reading code

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#72]
I'm trying to use the iconv package in Node to translate from ISO-8859-1 to UTF-8. I have a very small test program that fails. Hopefully someone more experienced in Node and encodings can help find the problem. Thanks in advance. 

Here's a small test app, that fails. I've included the JS source and a package.json.

https://gist.github.com/scripting/f68093b4da471028a821c3da467c62af

It reads a file through request, runs it through iconv, in a way that I think should properly decode it. It does _something,_ but what comes back is not the proper decoding. Something like this:

`Uhr eine 28-jï¿½hrige, aus Afghanistan`

Any help much appreciated. I know I'm calling it wrong, or something. 

Dave

**Comment by papascott** [comment]
request seems to assume that it's getting utf8 by default. When I set an encoding option, it seems to work. 

https://gist.github.com/papascott/c1ea2958d6aea935433873d60b58e6fe

**Comment by ronw23** [comment]
The above answer is almost right, but encoding should be null and then passed to iconv. If encoding is latin1, you'll get a double encoding.

**Comment by papascott** [comment]
I just noticed my mistake. :-) I can't get `encoding: null` to work for me, but with `encoding: "latin1"`I don't need iconv at all.

https://gist.github.com/papascott/d81264223a5d492af040ea6f0277e041

**Comment by scripting** [comment]
Scott, I'm seeing the same here. I am very confused by all this stuff. I'm going to keep reading and trying stuff out. Thank you for the help. ;-)

**Comment by scripting** [comment]
@ronw23 -- have you run any code? I've tried all the combinations with no luck.

**Comment by ronw23** [comment]
This is what I'm running and I'm seeing proper UTF-8:

https://gist.github.com/ronw23/bb1fd559c1487196d3a4a9e36620c079

**Comment by scripting** [comment]
It worked here too, but I can't see what changed.

**Comment by scripting** [comment]
But when I put the code in the "real" app -- I see the old behavior. 

Oy.

**Comment by scripting** [comment]
I take it back. It is working. The problem now seems to be happening when I pass the text to feedParser. Have to check that out now.

**Comment by scripting** [comment]
Aaaaand we have a win.

So I have it working here, now the next thing is to package it up and ship it.

I decided to make it easier to do feed parsing, so I can just drop it into an app, even if the source isn't the web. Sometimes you have feeds in other places. 

Thank you Scott and Ron for your help! :-)

**Comment by scripting** [comment]
BTW -- I've packaged this up as an NPM package. Here's some example code showing how it's used. 

https://github.com/scripting/feedRead/blob/master/testing/test.js

I've integrated it into feedBase, so it's running in a live app now.
