### ISSUE TITLE
Problem with node-debug

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#81]
Here's a quick video that demonstrates a problem I have with node-debug.

https://youtu.be/NjXz1apuG2o

Any help much appreciated! :-)

**Comment by june07** [comment]
Use node --inspect and https://june07.com/nim

**Comment by scripting** [comment]
Thank you. It worked. I wrote it up here.

http://scripting.com/2018/05/25/133439.html

Dave

**Comment by scripting** [comment]
Follow-up question.

I want to set a breakpoint when the program starts up.

I tried `node --inspect-brk test.js`, but it says it's a bad option.

It's made it much more fun to work on server stuff, btw. I can really get in there and see what's happening. It's not a chore anymore. ;-)

**Comment by june07** [comment]
Depending on the node version, you may have to use --inspect with
--debug-brk... Which by the way is deprecated in newer versions of Node.js.

See (among many other places)
https://github.com/Microsoft/vscode/issues/32529
for more info about it.
