### ISSUE TITLE
Potential Disqus alternative: Discourse

### ISSUE THREAD

**Issue by zackfern** [scripting/Scripting-News#84]
Hey Dave! Long time listener, first time caller.

[You mentioned](http://scripting.com/2018/06/02/134755.html) that you were looking for an alternative to Disqus because they've started embedding objectionable ads.

One thing I've noticed people doing as an alternative is hosting a [Discourse forum](https://www.discourse.org/) and embedding topics via iFrames to replace comments. They've got a pretty robust [how-to page](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963) describing this pattern, plus it looks like you can setup polling on an RSS feed!

Discourse itself is pretty easy to [setup using Docker](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md) and, I feel, has a pretty nice administrative interface. 

Might be worth checking out if there aren't any other viable Disqus alternatives. Good luck finding your replacement! :)

**Comment by andrewshell** [comment]
Dave, you also might want to take a look at https://schnack.cool
