### ISSUE TITLE
Design aspects of your posts / micro posts / links

### ISSUE THREAD

**Issue by briandigital** [scripting/Scripting-News#85]
Dave, I feel awkward posting this question here, but on the advice of your about page, here goes…

Have you ever written anything about your blog design? Specifically, on the homepage, you have what I'd call "Articles" (traditional, titled blog posts so to speak) mixed in with "Notes" (microposts without title, tweet-like [and for you some are tweets]). Separately, you have a tab for links, which appear to be individual yet they seem to be grouped by day instead. I'd be wildly curious about how you chose that structure, especially as I am making the decisions on my own re-starting-from-scratch site.

> Only steal from the best.

Thanks.

**Comment by scripting** [comment]
The design of the blog tab goes all the way back to the beginning of Scripting News. 

It gives me a notepad, a place to write, that's super easy for me. 

I use an outliner to write, maybe that provides a clue. ;-)

Here's a screen shot of the last few day with yesterday expanded.

![image](https://user-images.githubusercontent.com/1686843/42109930-623ae65a-7bad-11e8-9d9c-3f56960d46ba.png)

The Links tab is my linkblog, which I do using Radio3. While I have tried a lot of formats out for the blog part, the linkblog has been consistent, in the current format.

I guess the answer is that it isn't really designed, it's just the way it came out. 

"It's even worse than it appears."

Dave

**Comment by briandigital** [comment]
> I guess the answer is that it isn't really designed, it's just the way it came out.

Haha. Reminds me of what my old boss [coined as "Self-design".](https://articles.uie.com/design_decision_styles/).

Haha. I had this scenario on my list of possible explanations. It's interesting to see the backend of production. If you're ever looking for post topics, a peak behind the scenes of your daily blogging workflow, why/how you post something, what gets syndicated to Twitter, would probably be interesting to people beyond just me. 

Thanks for the response.

All the best,
~brian
