### ISSUE TITLE
RSS-in-JSON - Namespaces

### ISSUE THREAD

**Issue by ttepasse** [scripting/Scripting-News#9]
The Scripting News RSS-in-JSON Feed also serialises information which in an XML feed would exist in the [source namespace](http://source.smallpict.com/2014/07/12/theSourceNamespace.html) (Btw: see footnote). That feed somewhat mirrors XMLs namespace infrastructure: there is an xmlns namespace declaration which binds the prefix `source` to the URI of the source namespace. Later there are properties which look like Qualified Names in XML. 

For an XML processor the following snippets are exactly the same:

```xml
<channel xmlns:source="http://source.scripting.com/">
  ...
  <source:account service="twitter">davewiner</source:account>
  <source:account service="facebook">dave.winer.12</source:account>
  <source:account service="github">scripting</source:account>
  <source:account service="linkedin">scripting</source:account>
  <source:localTime>Tue, June 6, 2017 8:30 AM EDT</source:localTime>
  ...
</channel>
```
and
```xml
<channel xmlns:origin="http://source.scripting.com/">
  ...
  <origin:account service="twitter">davewiner</origin:account>
  <origin:account service="facebook">dave.winer.12</origin:account>
  <origin:account service="github">scripting</origin:account>
  <origin:account service="linkedin">scripting</origin:account>
  <origin:localTime>Tue, June 6, 2017 8:30 AM EDT</origin:localTime>
  ...
</channel>
```

… because the prefix doesn't matter but the URI to which the prefix is bound to.

What the [RSS-in-JSON spec](https://github.com/scripting/Scripting-News/blob/master/rss-in-json/README.md) doesn't answer: Should a parser for that format also implement XMLs namespacing mechanism? E.g. should it carry a binding from prefixes to namespace URIs and should it have a notion of [Qualified Names](https://www.w3.org/TR/xml-names/#ns-qualnames) to interpret different prefixes for the same namespace the same way?

And if not: There are a lot of RSS extensions out there, from Media RSS, some usage of Atom elements in RSS, the Content Module to iTunes’ extension, all in their own namespace. How can one use elements from this extensions, if one doesn't have a namespacing mechanism?

---

Small footnote: I just realised that the [source namespace spec](http://source.scripting.com) never mentions the URI for the namespace. One can look into Scripting News’ feed, of course, but it would be nice to have something important like that in the spec.

**Comment by scripting** [comment]
Thanks for the comments. Here are my responses.

1. This readme isn't documenting the Scripting News feed, so it wouldn't be in scope to explain the _source_ namespace. It's just part of an example.

2. The processor of a RSS-in-JSON feed would have to do whatever is needed to make sense of the content of the feed. If it contains namespace declarations, then it would have to understand what they are and how they work. Luckily they are well-defined in XML world.  I'm staying inside a very tight scope here, talking about how to translate an XML-based RSS feed  to using JSON syntax. Nothing more.

**Comment by dodyg** [comment]
The thing is that if the RSS 2.0 extension mechanism is not handled in this JSON format, people will just add extra properties to the format and we'll end up in a mess. 

Extensions for example can be accommodated by an extension array 
e.g (media RSS : http://www.rssboard.org/media-rss#primary-elements)
```
"extensions: {
   "media" : {
          "url":"http://www.foo.com/movie.mov"
  "fileSize":"12216320"
  "type":"video/quicktime"
  "medium":"video"
  "isDefault":"true"
  "expression":"full"
  "bitrate":"128"
  "framerate":"25"
  "samplingrate":"44.1"
  "channels":"2"
  "duration":"185"
  "height":"200"
  "width":"300"
  "lang":"en" 
   }
}
```

**Comment by scripting** [comment]
Dody, I don't understand the issue you're raising. 

You say "if the RSS 2.0 extension mechanism is not handled in this JSON format" -- in what way should they be "handled?"

Not sure what you want me to take away from this.

**Comment by dodyg** [comment]
Ah never mind. I missed reading the namespace handling section in the readme.

```rss must also contain a property declaring each namespace it uses. The name of each begins with xmlns followed by : followed by the name you want to use for the namespace in the feed. The value is the URL used in the namespace declaration in the XML feed.```
