### ISSUE TITLE
Puzzling Mac download behavior

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#93]
On the Frontier-User list, Frank Meeuwsen <a href="https://groups.google.com/forum/#!topic/frontier-user/i13XoQ6Rq_I">reports</a> a problem using the <a href="http://home.opml.org/#1506805469000">DMG</a> that installs the OPML Editor. He downloads the DMG, extracts the OPML folder, runs the app, and gets a dialog asking where the root is. You're not supposed to get this dialog. OPML.app is supposed to look for and automatically open opml.root in the same folder as the app. This isn't happening.

I have been able to reproduce it here. To try to narrow down the problem, I created a virgin OPML folder, zipped it, copied it to another folder, unzipped it, ran the app and it worked as it's supposed to. I then uploaded the zipped file, downloaded it, unzipped as before, ran the app, and got the behavior Frank describes. If you want to try it, you can download the <a href="https://www.dropbox.com/s/39lkdbd5cu2kc5e/OPML.zip?dl=1">zip file</a> from my Dropbox.

I wrote a script to compare the original zip file with the downloaded file. They are identical. Something is happening when the zip file is uncompressed? Not sure. I don't have the ability to look inside the OPML app to see what's tripping it up. This is new behavior. I am having trouble coming up with theories to try.

**Comment by remorse** [comment]
Recent versions of Mac OS do a weird trick where they mount applications on a random path before running if the application hasn't been copied in the Finder (or something like that). If you're running the application, and you to go a terminal, and type`mount`, do you see the application mounted on a random folder?

I think the term to search on is "App(lication) Translocation"? I have a note in my scrapbook that goes:

`````
2017-11-13 [Nov 13] 04:09 PM

Command to remove translocation from an application in Mac OS High Sierra

	xattr -dr com.apple.quarantine "/Applications/Keyboard Maestro.app"
`````

I'm not sure if this is your problem or not, but it reminds me of some issues I was having which were solved by this. I'm not sure how to work around it though from the point of view of the application developer.

**Comment by tedchoward** [comment]
More info here:

https://github.com/tedchoward/Frontier/issues/9
